ALTER TABLE public.stores 
ADD COLUMN IF NOT EXISTS pickup_zip TEXT,
ADD COLUMN IF NOT EXISTS pickup_lat NUMERIC,
ADD COLUMN IF NOT EXISTS pickup_lng NUMERIC,
ADD COLUMN IF NOT EXISTS pickup_contact_name TEXT,
ADD COLUMN IF NOT EXISTS pickup_email TEXT,
ADD COLUMN IF NOT EXISTS pickup_is_residential BOOLEAN DEFAULT false;
